{{- $fullName := include "logto.fullname" . -}}
{{- $labels := include "logto.labels" . -}}

{{- $services := include "logto.serviceDict" . | fromYaml -}}
{{- range $key, $svc := $services }}
{{- $route := (ternary $.Values.console.httpRoute $.Values.httpRoute (eq $key "admin")) -}}
{{- if $route.enabled }}
{{- $parentRefs := $route.parentRefs | default list }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include (printf "logto.%sServiceName" $key) . }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $parentRefs }}
  parentRefs:
    {{- toYaml $parentRefs | nindent 4 }}
  {{- end }}
  hostnames:
    {{- range $route.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    {{- if $route.rules }}
      {{- toYaml $route.rules | nindent 4 }}
    {{- else }}
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: {{ include (printf "logto.%sServiceName" $key) . }}
          port: {{ include (printf "logto.%sServicePort" $key) . }}
    {{- end }}
{{- end }}
{{- end }}
